---
- name: Set timezone
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install essential packages
  ansible.builtin.apt:
    name: "{{ common_packages + common_extra_packages }}"
    state: present

- name: Set system locale
  community.general.locale_gen:
    name: "{{ common_locale }}"
    state: present

- name: Remove unused packages
  ansible.builtin.apt:
    autoremove: true
    purge: true
