#!/usr/bin/bash

DOTFILES_DIR="$HOME/.dotfiles"
SSH_DIR="$HOME/.ssh"

function _cmd {
  echo "Running: $1"
  eval "$1"
}

function detect_os {
  [[ -f /etc/os-release ]] && source /etc/os-release && echo "$ID" || echo "unknown"
}


function install_ansible {
  case $1 in
  ubuntu)
    _cmd "sudo apt-get update"
    _cmd "sudo apt-get install -y software-properties-common"
    _cmd "sudo add-apt-repository --yes --update ppa:ansible/ansible"
    _cmd "sudo apt-get install -y ansible"
    ;;
  fedora)
    _cmd "sudo dnf update -y"
    _cmd "sudo dnf install -y ansible"
    ;;
  *)
    echo "Unsupported OS: $1"
    echo "Supported OS: ubuntu, fedora"
    ;;
  esac
}


# Main execution
os=$(detect_os)
echo "Detected OS: $os"
install_ansible "$os"

#ansible-playbook "$DOTFILES_DIR/main.yml" --limit local --ask-become-pass
