---
- name: "Validate that the Bitwarden secret ID is provided"
  ansible.builtin.assert:
    that:
      - bws_secret_id | length > 0
    fail_msg: "The 'bws_secret_id' variable is required for this role."
    quiet: true

- name: "Ensure the .ssh directory exists with correct permissions"
  ansible.builtin.file:
    path: "{{ dest_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid | default(ansible_user_id) }}"
    mode: "0700"

- name: "Deploy private SSH key from Bitwarden Secrets Manager"
  ansible.builtin.copy:
    dest: "{{ dest_dir }}/{{ dest_filename }}"
    content: "{{ lookup('community.general.bitwarden_secrets_manager', bws_secret_id, bws_access_token=bws_access_token).value }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid | default(ansible_user_id) }}"
    mode: "0600"
