---
# Variables applied to all LXC containers

# LLDAP - LDAP authentication
lldap_ldap_server: "ldap://lldap.g4ng.es:3890"
lldap_ldap_basedn: "dc=g4ng,dc=es"
lldap_test_user: "g4ng"

# Common packages for LXC nodes (in addition to role defaults)
common_extra_packages: []
